# Generic netgraph topology builder
# Replaces old ng_builder, ng_builder_mbuf, and ng_builder_wire_verify

PROG=	ng_builder_generic
SRCS=	ng_builder_generic.c
LDADD=	-lnetgraph

.include <bsd.prog.mk>
